# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=16

# Drcula color scheme
background: &background 282a36ff
foreground: &foreground f8f8f2ff
black: &black 21222cff
red: &red ff5555ff
green: &green 50fa7bff
yellow: &yellow f1fa8cff
blue: &blue bd93f9ff
magenta: &magenta ff79c6ff
cyan: &cyan 8be9fdff
white: &white f8f8f2ff
bright_black: &bright_black 6272a4ff
bright_red: &bright_red ff6e6eff
bright_green: &bright_green 69ff94ff
bright_yellow: &bright_yellow ffffa5ff
bright_blue: &bright_blue d6acffff
bright_magenta: &bright_magenta ff92dfff
bright_cyan: &bright_cyan a4ffffff
bright_white: &bright_white ffffffff

std_underline: &std_underline {underline: { size: 2, color: *magenta}}

# This is THE bar configuration
bar:
  height: 30
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: Monospace:pixelsize=18:style=bold

  foreground: *foreground
  background: *background

  border:
    width: 2
    color: *blue
    margin: 0
    top-margin: 0

  left:
    - label:
        content:
          string:
            on-click: fuzzel
            text: ïŒƒ
            foreground: 1491CEff
            font: Monospace:pixelsize=20

    - i3:
        anchors: # Not used (directly) by f00bar; used here to avoid duplication
          - string: &i3_common {left-margin: 3, right-margin: 13, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}"}
          - string: &surfing {<<: *i3_common, text: ï‰©, font: *awesome_brands}
          - focused: &focused
              deco: {stack: [background: {color: *blue}, <<: *std_underline]}
          - invisible: &invisible {foreground: *bright_black}
          - urgent: &urgent
              foreground: *black
              deco: {stack: [background: {color: *red}, <<: *std_underline]}
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: *bright_red}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
        sort: ascending
        content:
          "":
            map:
              left-margin: 3
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
          surfing:
            map:
              conditions:
                state == focused: {string: {<<: [*surfing, *focused]}}
                state == unfocused: {string: {<<: *surfing}}
                state == invisible: {string: {<<: [*surfing, *invisible]}}
                state == urgent:    {string: {<<: [*surfing, *urgent]}}
          current:
            map: {left-margin: 20, <<: *i3_mode}

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", max: 10, foreground: *magenta}
                - string: {text: ": {title}", max: 35}

  center:
    - clock:
        time-format: "%H:%M"
        date-format: "%d %b %Y"
        content:
          - string: {text: ï‰´, font: *awesome, foreground: *green}
          - string: {text: " {date}", right-margin: 5, foreground: *green, on-click: "setbg"}
          - string: {text: ï€—, font: *awesome}
          - string: {text: " {time}"}

    - script:
        path: /home/mzeinali/.config/yambar/khorshidi_date
        content:
          - string: {text: ï³, font: *awesome, foreground: *yellow}
          - string: {text: "{khorshidi_date}", foreground: *yellow}

  right:
    - removables:
        anchors:
          drive: &drive { text: ó±Šž, font: *awesome}
          optical: &optical {text: ï”Ÿ, font: *awesome}
        spacing: 5
        content:
          map:
            conditions:
              ~mounted:
                map:
                  on-click: menumount
                  conditions:
                    ~optical: [{string: *drive}, {string: {text: " {label}"}}]
                    optical: [{string: *optical}, {string: {text: " {label}"}}]
              mounted:
                map:
                  on-click: menuumount
                  conditions:
                    ~optical:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: " {label}"}
                    optical:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: " {label}"}

    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: " {linear_volume}%", foreground: *red}}
              ~muted: {string: {text: " {linear_volume}%", foreground: *cyan}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        on-click: /bin/sh -c "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                        conditions:
                          muted:
                            map:
                              conditions:
                                form_factor == headset:
                                  string: {text: ó°‹, font: *awesome, foreground: *red}
                                form_factor == headphone:
                                  string: {text: ó°‹, font: *awesome, foreground: *red}
                              default: {string: {text: ï‘¦ , foreground: *red}}
                          form_factor == headset:
                            string: {text: ó°‹Ž, font: *awesome, foreground: *cyan}
                          form_factor == headphone:
                            string: {text: ó°‹Ž, font: *awesome, foreground: *cyan}
                        default:
                          - ramp:
                              tag: linear_volume
                              items:
                                - string: {text: ï€¦, font: *awesome, foreground: *cyan}
                                - string: {text: ï€§, font: *awesome, foreground: *cyan}
                                - string: {text: ï€§, font: *awesome, foreground: *cyan}
                                - string: {text: ï€§, font: *awesome, foreground: *cyan}
                                - string: {text: ï€¨, font: *awesome, foreground: *cyan} 
                    type == "source":
                      map:
                        on-click: /bin/sh -c "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
                        conditions:
                          muted: {string: {text: " ï„± ", foreground: *red}}
                        default: {string: {text: " ðŸŽ™", foreground: *cyan}}
              - map:
                  <<: *volume

#CONFIGS
    - sway-xkb:
        identifiers: [1:1:AT_Translated_Set_2_keyboard]
        content:
          - string: {text: ï„œ, font: *awesome, foreground: *bright_magenta}
          - string: {text: " {layout}", foreground: *bright_magenta}

    - label:
        content:
          string:
            on-click: sysact
            text: "ï€‘  "
            font: *awesome
            foreground: *red

